on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno_ci:
    uses: cross-org/workflows/.github/workflows/deno-ci.yml@main
    with:
      entrypoint: src/ipc.ts
      lint_docs: false
  bun_ci:
    uses: cross-org/workflows/.github/workflows/bun-ci.yml@main
    with:
      jsr_dependencies: "@cross/test @std/assert @std/async @std/path cross/fs"
  node_ci:
    uses: cross-org/workflows/.github/workflows/node-ci.yml@main
    with:
      jsr_dependencies: "@cross/test @std/assert @std/async @std/path cross/fs"
      test_target: "src/**/*.test.ts"